In [31]:
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings("ignore")

In [32]:
df = pd.read_csv("../data/sales.csv")

df.head()

,OrderID,CustomerID,Date,City,Category,Product,Price,Quantity,Discount,Payment,Revenue
0,1,452,2025-11-24,Kazan,Smartphone,Samsung Galaxy S24,74990,1,10,Card,67491.0
1,2,43,2025-05-06,Moscow,Laptop,MacBook Air M3,139990,1,0,Card,139990.0
2,3,431,2025-12-13,Moscow,Tablet,iPad Air,69990,1,0,Card,69990.0
3,4,192,2025-01-17,Samara,Smartphone,iPhone 15,89990,1,0,Card,89990.0
4,5,94,2025-09-16,Kazan,Monitor,LG UltraWide,34990,1,0,Card,34990.0

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   OrderID     20000 non-null  int64
 1   CustomerID  20000 non-null  int64
 2   Date        20000 non-null  object
 3   City        20000 non-null  object
 4   Category    20000 non-null  object
 5   Product     20000 non-null  object
 6   Price       20000 non-null  int64
 7   Quantity    20000 non-null  int64
 8   Discount    20000 non-null  int64
 9   Payment     20000 non-null  object
 10  Revenue     20000 non-null  float64
dtypes: float64(1), int64(5), object(5)
memory usage: 1.7+ MB

In [34]:
print("Количество заказов:", df["OrderID"].nunique())
print("Количество клиентов:", df["CustomerID"].nunique())
print("Общая выручка:", round(df["Revenue"].sum(), 2))
print("Средний чек:", round(df["Revenue"].mean(), 2))

Количество заказов: 20000
Количество клиентов: 500
Общая выручка: 1093249790.5
Средний чек: 54662.49

In [35]:
category_analysis = (
    df.groupby("Category")
    .agg(
        Orders=("OrderID", "count"),
        Revenue=("Revenue", "sum")
    )
    .sort_values("Revenue", ascending=False)
)

category_analysis

            Orders      Revenue
Category
Laptop        3968  348327490.0
Smartphone    4006  278041159.5
Tablet        2691  132941187.0
Smartwatch    2594  128508559.5
Monitor       2714  104708311.5
Headphones    4027  100723083.0

In [36]:
city_analysis = (
    df.groupby("City")
    .agg(
        Orders=("OrderID", "count"),
        Revenue=("Revenue", "sum")
    )
    .sort_values("Revenue", ascending=False)
)

city_analysis

                  Orders      Revenue
City
Moscow              6196  337972341.5
Saint Petersburg    3444  187841411.5
Kazan               2087  115891993.5
Ufa                 1755   95717198.5
Novosibirsk         1581   87668531.0
Yekaterinburg       1583   86182197.5
Voronezh            1209   65230368.5
Samara              1148   63206348.5
Perm                 997   53539400.0

In [37]:
top_products = (
    df.groupby("Product")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products

Product
MacBook Air M3        180580100.5
iPhone 15             111506609.0
Samsung Galaxy S24     94536143.5
iPad Air               86980072.5
Lenovo IdeaPad         86493642.0
ASUS VivoBook          81253747.5
Apple Watch            77736949.5
Xiaomi 14              71998407.0
Samsung Odyssey        60515941.5
Sony WH-1000XM5        52683380.5
Name: Revenue, dtype: float64

In [38]:
discount_analysis = (
    df.groupby("Discount")["Revenue"]
    .sum()
)

discount_analysis

Discount
0     526176190.0
5     250533753.0
10    259792992.0
15     20975730.5
20     17696560.0
25     18074565.0
Name: Revenue, dtype: float64

In [39]:
print("Основные выводы:")
print("- Больше всего выручки приносят категории с высокой стоимостью товаров.")
print("- Москва и Санкт-Петербург являются крупнейшими рынками.")
print("- В период повышенного спроса увеличивается количество заказов.")
print("- Скидки влияют на продажи и позволяют увеличивать объем заказов.")

Основные выводы:
- Больше всего выручки приносят категории с высокой стоимостью товаров.
- Москва и Санкт-Петербург являются крупнейшими рынками.
- В период повышенного спроса увеличивается количество заказов.
- Скидки влияют на продажи и позволяют увеличивать объем заказов.

In [40]:
df.columns

Index(['OrderID', 'CustomerID', 'Date', 'City', 'Category', 'Product', 'Price',
       'Quantity', 'Discount', 'Payment', 'Revenue'],
      dtype='object')

In [41]:
print("Количество заказов:", df["OrderID"].nunique())
print("Количество клиентов:", df["CustomerID"].nunique())
print("Общая выручка:", round(df["Revenue"].sum(), 2))
print("Средняя выручка с заказа:", round(df["Revenue"].mean(), 2))

Количество заказов: 20000
Количество клиентов: 500
Общая выручка: 1093249790.5
Средняя выручка с заказа: 54662.49

In [42]:
category_sales = (
    df.groupby("Category")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

category_sales

Category
Laptop        348327490.0
Smartphone    278041159.5
Tablet        132941187.0
Smartwatch    128508559.5
Monitor       104708311.5
Headphones    100723083.0
Name: Revenue, dtype: float64

In [43]:
city_sales = (
    df.groupby("City")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

city_sales

City
Moscow              337972341.5
Saint Petersburg    187841411.5
Kazan               115891993.5
Ufa                  95717198.5
Novosibirsk          87668531.0
Yekaterinburg        86182197.5
Voronezh             65230368.5
Samara               63206348.5
Perm                 53539400.0
Name: Revenue, dtype: float64

In [44]:
top_products = (
    df.groupby("Product")["Revenue"]
    .sum()
    .sort_values(ascending=False)
    .head(10)
)

top_products

Product
MacBook Air M3        180580100.5
iPhone 15             111506609.0
Samsung Galaxy S24     94536143.5
iPad Air               86980072.5
Lenovo IdeaPad         86493642.0
ASUS VivoBook          81253747.5
Apple Watch            77736949.5
Xiaomi 14              71998407.0
Samsung Odyssey        60515941.5
Sony WH-1000XM5        52683380.5
Name: Revenue, dtype: float64

In [45]:
discount_analysis = (
    df.groupby("Discount")["Revenue"]
    .mean()
    .sort_values(ascending=False)
)

discount_analysis

Discount
0     57261.529002
5     55013.999341
10    51958.598400
15    48442.795612
20    44352.280702
25    42528.388235
Name: Revenue, dtype: float64

In [46]:
payment_analysis = (
    df.groupby("Payment")["Revenue"]
    .sum()
    .sort_values(ascending=False)
)

payment_analysis

Payment
Card    758887509.0
SBP     243420266.5
Cash     90942015.0
Name: Revenue, dtype: float64

По результатам анализа были изучены основные показатели продаж интернет-магазина электроники.

Были рассчитаны:
- общая выручка и средний чек;
- продажи по категориям товаров;
- наиболее прибыльные города и товары;
- влияние скидок и способов оплаты на выручку.

Анализ позволил выявить наиболее успешные направления продаж и получить представление о структуре доходов магазина.